// <auto-generated />
using Contacts_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contactcs_API.Migrations
{
    [DbContext(typeof(ContactsContext))]
    partial class ContactsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contactcs_API.Models.Contact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("birthday");

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.Property<string>("surname");

                    b.HasKey("id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new { id = 1, birthday = "18.05.1990", email = "o@outlook.com", name = "Михаил", surname = "Белоусов" },
                        new { id = 2, birthday = "19.05.1992", email = "hr6zdl@yandex.ru", name = "Руслан", surname = "Лапин" },
                        new { id = 3, birthday = "29.06.1995", email = "kaft93x@outlook.com", name = "Павел", surname = "Исаков" },
                        new { id = 4, birthday = "20.05.1995", email = "dcu@yandex.ru", name = "Пётр", surname = "Мельников" },
                        new { id = 5, birthday = "21.05.1998", email = "pa5h@mail.ru", name = "Витольд", surname = "Алчевский" },
                        new { id = 6, birthday = "10.05.2002", email = "281av0@gmail.com", name = "Йомер", surname = "Дзюба" },
                        new { id = 7, birthday = "13.02.2007", email = "8edmfh@outlook.com", name = "Филипп", surname = "Жуков" },
                        new { id = 8, birthday = "22.04.2008", email = "sfn13i@mail.ru", name = "Дарий", surname = "Титов" },
                        new { id = 9, birthday = "14.12.2020", email = "g0orc3x1@outlook.com", name = "Цезарь", surname = "Королёв" },
                        new { id = 10, birthday = "14.12.2020", email = "rv7bp@gmail.com", name = "Алёна", surname = "Скляренко" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
